### PR TITLE
[schema] Export hcl2shum.HCL2ValueFromConfigValue.

### PR DESCRIPTION
**Pull request by pgavlin**
We need this in the bridge.

### CODE REVIEW

**Comment by stack72** [comment]
@pgavlin I did this without exporting it and creating an internal shim in the bridge that would allow me to load this

This will work of course :)

**Review by stack72 — APPROVED** [review]

**Comment by pgavlin** [comment]
> I did this without exporting it and creating an internal shim in the bridge that would allow me to load this

Ah right, I think I saw some similar code in the various providers to achieve access to internals. That seems like a cleaner solution as far as maintenance goes. I'll give that a shot.

**Comment by pgavlin** [comment]
> > I did this without exporting it and creating an internal shim in the bridge that would allow me to load this
> 
> Ah right, I think I saw some similar code in the various providers to achieve access to internals. That seems like a cleaner solution as far as maintenance goes. I'll give that a shot.

Actually, I'm curious--did that work when consuming pulumi-terraform-bridge from another module? That approach requires that the `replace` directives are also present in consuming repos, yeah?

**Comment by pgavlin** [comment]
I'm going to go ahead and merge this to avoid downstream replaces.

**Pull request merged**
